### ISSUE TITLE
Deprecate "-" in favor of "--" in concise parsing mode

### ISSUE THREAD

**Issue by patrick-steele-idem** [marko-js/htmljs-parser#43]
__OLD:__

```xml
h1 - Hello World!
```

__NEW:__

```xml
h1 -- Hello World!
```

# Why?

With the change to support spaces in any attribute values in, the usage of a single hyphen (AKA minus sign) is now ambiguous. For example, given the following input:

```
todos remaining = total  - completed
```

This could be interpreted as either of the following:

```html
<todos remaining=(total - completed)/>
```

```html
<todos remaining=total>completed</todos>
```

To avoid the ambiguity, we are now requiring two hyphens (surrounded by spaces). While two hyphens can be used as a unary operator JavaScript expressions, it would never appear with spaces before and after (" -- ").

# Additional details

## Concise mode text
`-` to start an html block will be deprecated in v3. Two (or more) dashes will be required.  This is partly to allow `var foo = 3 - 2;` without any ambiguity and keep consistency throughout the language.   

### Two (or more) dashes followed by a space and some text indicate one line of an html text block:
```
div class="foo" -- Hello World
```
```
div class="foo" 
    -- Hello World
```

### Two (or more) dashes followed by a line break indicate the beginning of a multiline html text block.  The lines that follow must maintain the indentation or they will enter back into concise mode as a sibling tag:
```
div class="foo" -- 
    Hello World
    What's up?
span -- Meh
```
```
div class="foo" 
    -- 
    Hello World
    What's up?
span -- Meh
```

### A multiline html text block can be ended by the same number of dashes that opened it so that additional children can be added to the parent tag:
```
div class="foo" -- 
    Hello World
    What's up?
    --
    span -- Meh.
```
```
div class="foo" 
    -- 
    Hello World
    What's up?
    --
    span -- Meh.
```

Related Pull Requests:

- [PR #42 - Whitespace, commas, semicolons.](https://github.com/marko-js/htmljs-parser/pull/42)

**Comment by rgagnon24** [comment]
This change actually breaks templates that might have a line of text containing a series of dashes and spaces for a divider. even if they are outside of  `${...}`

Example:
```
This is my text template
- - - - - - - - - - - - - - -
A signature line

```

**Comment by patrick-steele-idem** [comment]
@rgagnon24 `-----` at the root would have always been issue so I am not sure I quite understand how the change would have broke something. You can do the following:

```
--
This is my text template
- - - - - - - - - - - - - - -
A signature line
--
```

HTML output will be:

```
This is my text template
- - - - - - - - - - - - - - -
A signature line
```

**Comment by rgagnon24** [comment]
Maybe some context....

We use Marko to produce email content... one template for the text version, and another to produce the html version.  It is during the production of the text version of the email that this deprecation warning shows up because it is parsing with "concise" and there seems no way to pass `concise: false` to marko in a way that would work.

If wrapping with `--` works, we can go with that, but there's was no documentation on that.
